# Funding sources for sponsoring PTowl.
# Uncomment and fill in any platforms you set up. All optional.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [Yami566]      # GitHub Sponsors (requires enabling on your account)
# patreon: ptowl         # Patreon username
# open_collective: ptowl # Open Collective slug
# ko_fi: ptowl           # Ko-fi username
# custom: ['https://ptowl.com']
